### ISSUE TITLE
Determine how to figure dealing with time in JS

### ISSUE THREAD

**Issue by Mikerah** [ChainSafeSystems/gossipsub-js#14]
In GossipSub, we need to store the latest publish message and periodically run the heartbeat operation. The first can be easily done with default JS functionality but I don't think this is the case for the second. An initial Google search brings up using Promises to get similar functionality to Go's `time.sleep` but it's still not the same since it only pauses the function in which the promise is called.

We need to find a way to do this deterministically and make sure that we don't get unnecessary hangs in our code.

**Comment by raulk** [comment]
`setInterval` and `setTimeout`?

**Comment by Mikerah** [comment]
It seems like `setInterval` and `setTimeout` are legacy features in Firefox. It is not recommend to use them by [MDN](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Code_snippets/Timers). However, that pertains to extenseions. It still appears to be supported in Node.js. I think in the meantime, `setInterval` and `setTimeout` are sufficient for our current needs.

**Comment by vasco-santos** [comment]
We are using `setInterval` and `setTimeout` in our codebase in a ton of places. So, I would say that you can use them for now. In a better timing, we may consider other options for this.

**Comment by Mikerah** [comment]
@raulk and @vasco-santos thanks for your input.
