### ISSUE TITLE
Add CI to this repo

### ISSUE THREAD

**Issue by Mikerah** [ChainSafeSystems/gossipsub-js#17]
I don't have access to the chainsafe travis account so I am creating this issue. The libp2p team suggests that we use [aegir](https://github.com/ipfs/aegir).

cc'ing @GregTheGreek and @priom.

**Comment by GregTheGreek** [comment]
You should have access, because you're apart of the organization.

make sure to got to travis-ci.org and not .com

**Comment by Mikerah** [comment]
Resolved by https://github.com/ChainSafeSystems/gossipsub-js/pull/18
